### ISSUE TITLE
line-continuation makes incorrect lnum

### ISSUE THREAD

**Issue by Kuniwak** [ynkdir/vim-vimlparser#16]
```vim
let g:a = deepcopy(
      \ g:v["a"])
            ^
```

The lnum of the node `"a"` is not correct (`i` and `col` are correct).
In this example, the lnum is 2 but correct lnum is 3.

**Comment by ynkdir** [comment]
Thank you for bug report.  I have fixed.
https://github.com/ynkdir/vim-vimlparser/commit/7fed00769773879e676a3d2685b3d2367e6b2058

**Comment by Kuniwak** [comment]
Thanks!
