### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by tony** [ynkdir/vim-vimlparser#17]
Can you license this MIT?

See https://github.com/Kuniwak/vint.

**Comment by mattn** [comment]
Seems to be public domain. But want for @ynkdir 
https://github.com/ynkdir/vim-vimlparser/blob/master/autoload/vimlparser.vim

**Comment by ynkdir** [comment]
vimlparser is in the public domain.
Use, modify, and distribute of vimlparser is unlimited.
